import { Project, PROJECT_CATEGORIES } from './types';

export const maintenanceProjects: Project[] = [
    {
        id: 150,
        name: "Barclays Capital, 745 7th Ave.",
        category: PROJECT_CATEGORIES.ELECTRICAL_MAINTENANCE,
        featured: false,
    },
    {
        id: 151,
        name: "JP Morgan Chase Branch Maintenance, Various Locations, NY, NJ, CT, Westchester County, Putnam County",
        category: PROJECT_CATEGORIES.ELECTRICAL_MAINTENANCE,
        featured: false,
    },
    {
        id: 152,
        name: "Ford Foundation Electrical Maintenance, 320 E. 43rd St., NY, NY",
        category: PROJECT_CATEGORIES.ELECTRICAL_MAINTENANCE,
        featured: false,
    },
    {
        id: 153,
        name: "UJA Federation of NY, 130 E. 59th St., NY, NY",
        category: PROJECT_CATEGORIES.ELECTRICAL_MAINTENANCE,
        featured: false,
    },
    {
        id: 154,
        name: "Willis Towers Watson, 200 Liberty St., NY, NY",
        category: PROJECT_CATEGORIES.ELECTRICAL_MAINTENANCE,
        featured: false,
    },
    {
        id: 155,
        name: "Wells Fargo Branch Maintenance, Various Locations",
        category: PROJECT_CATEGORIES.ELECTRICAL_MAINTENANCE,
        featured: false,
    },
    {
        id: 156,
        name: "Santander Bank Branch Maintenance, Various Locations",
        category: PROJECT_CATEGORIES.ELECTRICAL_MAINTENANCE,
        featured: false,
    },
];

export const projects: Project[] = [
    {
        id: 1,
        name: "277 Park Ave., Lobby Renovation",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 2,
        name: "Angelo Gordon / Forstman Leff, 245 Park Ave., Floors 26 & 24",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 3,
        name: "Arsenal Capital Partners, 277 Park Ave.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 4,
        name: "Barclays Capital, 745 7th Ave.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: true,
    },
    {
        id: 5,
        name: "Beacon Capital, 85 Broad St., Lobby",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 6,
        name: "BNY Mellon, Electrical Fit-Out Multiple Phases, 101 Barclay St.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 7,
        name: "Brigade Capital, 399 Park Ave., Floors 15 & 16",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 8,
        name: "CCMP Capital Advisors, 277 Park Ave., 27th Fl.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 9,
        name: "Citi Headquarters Bank Branch, 388 Greenwich St.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 10,
        name: "Customers Bank, 101 Park Ave., 27th Fl.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 11,
        name: "One Deutsche Bank, 10 Columbus Circle",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 12,
        name: "Deloitte, 2 Jericho Plaza, 3rd Fl Swing Space",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 13,
        name: "DZ Bank, 1 Vanderbilt Ave.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 14,
        name: "Ernst & Young, 1 Manhattan West",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 15,
        name: "First Data, 225 Liberty Street",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 16,
        name: "Fiserv, One Broadway, Electrical & Tele/Data",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 17,
        name: "Goldman Sachs & Co. (Various NYC locations)",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 18,
        name: "One Citi NY Interiors Amenities, 388 & 390 Greenwich St.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 19,
        name: "ING, 1133 Avenue of the Americas, NY, NY",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 20,
        name: "JP Morgan Chase Bank, 383 Madison Ave. ",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 21,
        name: "JP Morgan Chase Bank (Various NYC Branch Renovations & Maintenance)",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 22,
        name: "JP Morgan Chase, 450 W. 33rdSt., 9th Floor Telecom",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 23,
        name: "JP Morgan Chase, 237 Park Ave.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 24,
        name: "JP Morgan Chase, FRB Rockefeller Center Network Installation",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 25,
        name: "JP Morgan Chase, 270 Park Ave., High Rise Floors 40-44",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: true,
    },
    {
        id: 26,
        name: "Lazard Freres, 30 Rockefeller Plaza",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },

    {
        id: 28,
        name: "Morgan Stanley, 1 New York Plaza, Multiple Projects & Floors",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 29,
        name: "Morgan Stanley, 750 7th Ave., Floors 12,14,18,19 & 29",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 30,
        name: "Morgan Stanley, 522 5th Ave., 6th Fl.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 31,
        name: "National Financial Partners, 340 Madison Ave.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 32,
        name: "National Financial Partners, 200 Park Ave., 32nd Fl.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 33,
        name: "New York Stock Exchange, 11 Wall St., 8th Fl, Demo",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 34,
        name: "Pharo Management, 1370 Avenue of the Americas",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 35,
        name: "Raymond James Financial, 277 Park Ave.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 36,
        name: "Societe General, 245 Park Ave.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 37,
        name: "Sumitomo Mitsui Banking Corp., 277 Park Ave., 16th Fl.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 38,
        name: "TD Bank, 1 Vanderbilt Ave.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 39,
        name: "The Bank of China, 7 Bryant Park, NY, NY",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 40,
        name: "Wells Fargo, (Various Branch Renovations & Maintenance)",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 41,
        name: "Wells Fargo, 777 6th Ave.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 42,
        name: "US Trust, 114 W. 47th St",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 43,
        name: "Alvin Ailey Dance Theater, 405 W. 55th St.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 44,
        name: "Barnard College, 116thSt. & Broadway / 40 Claremont Ave.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 45,
        name: "Brooklyn Hospital Center, 121 Dekalb Ave., Brooklyn, NY",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 46,
        name: "Cardiovascular Research Foundation of NY, 111 E. 59th St.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 47,
        name: "Columbia University Hammer Health Science Building, 701W. 168th St.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 48,
        name: "Fordham University Arcade, 441 Fordham Rd., Bronx, NY",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 49,
        name: "International Rescue Committee, 122 E. 42nd St.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 50,
        name: "Memorial Sloan Kettering Cancer Center, 515 Madison Ave.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 51,
        name: "Memorial Sloan Kettering Cancer Center, 1246 1st Ave",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 52,
        name: "North Shore L.I.J Urgent Care Facilities (RegoPark & Flushing Locations)",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 53,
        name: "NYU, Various Locations, Moves/Adds/Changes, Maintenance & Repair",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 54,
        name: "NYU 75 Third Ave. Dormitories -3 Towers",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 55,
        name: "NYU, 19 Washington Square North",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 56,
        name: "NYU Alumni Hall, 33 Third Ave., Phase I & II",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 57,
        name: "NYU Downtown Ambulatory Care Center, 111 Broadway",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 58,
        name: "NYU Forbes, 60 5th Ave.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: true,
    },
    {
        id: 59,
        name: "NYU Medical Center, 550 1st Ave.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 60,
        name: "NYU School of Law, 22 Washington Square North",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 61,
        name: "NYU Tisch School of the Arts, 665 Broadway",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 62,
        name: "NYU Lillian Vernon Center for Creative Writing, 58 W. 10th St",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 63,
        name: "NYU Silver Hall, 100 Washington Square East",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 64,
        name: "NYU Hayden Hall, 33 Washington Square West",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 65,
        name: "NYU 25 W. 4th St., Floors SC-7",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 66,
        name: "Ronald McDonald House, 405 E. 73rd St.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 67,
        name: "St. John's University, Jamaica, NY (St. Albert's Hall, 2007 and Bent Hall, 2016)",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 68,
        name: "The Ford Foundation, 320 E. 43rd St.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 69,
        name: "The Judd Foundation, 101 Spring St.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 70,
        name: "UJA Federation of NY, 130 E. 59th St.",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 71,
        name: "Weill Cornell Medical Radiology, 186 Joralemon St., Brooklyn, NY",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 72,
        name: "32 Old Slip, Local Law 191, Various Floors",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 73,
        name: "375 Pearl St., New York, NY",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 74,
        name: "1015 Madison Ave., 3rd Floor",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 75,
        name: "Asics Times Square, 120 E. 42nd St",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 76,
        name: "Berkley Research Group, 810 7th Ave",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 77,
        name: "Boston Consulting, 430 Park Ave.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 78,
        name: "DSNY 17/18 Garage Roof & HVAC",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 79,
        name: "Facebook, 50 Hudson Yards",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: true,
    },
    {
        id: 80,
        name: "Federal Reserve LNY Checkpoint Booth, New York, NY",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 81,
        name: "Full Beauty Brands, 1 New York Plaza, Electrical & Telecom",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 82,
        name: "Google, 85 10thAve., 3rd Fl.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 83,
        name: "Google / Google-WebMD, 111 8th Ave",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 84,
        name: "Google Pier 57",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: true,
    },
    {
        id: 85,
        name: "Gucci (840 Madison Ave., 725 Fifth Ave.)",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 86,
        name: "Solomon R. Guggenheim Museum, 1071 5th Ave. & 345 Hudson St. (Office)",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 87,
        name: "Korn Ferry International, 200 Park Ave.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 88,
        name: "Local Union #28 Sheet Metal Workers Union, SMART Education Fund",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 89,
        name: "L'Oreal USA, 575 Fifth Ave.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 90,
        name: "Macy's Herald Square, 151 W. 34th St.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 91,
        name: "Major League Baseball HQ, 245 Park Ave.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 92,
        name: "Martha Stewart Living Omnimedia, 601 W. 26th St.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 93,
        name: "Monster.com, 622 Third Ave.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 94,
        name: "Molloy College Space at 50 Broadway, New York, NY",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 95,
        name: "New York Police Academy, College Point, NY",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 96,
        name: "Noguchi Museum, 37-30 Vernon Blvd., LIC, NY",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 97,
        name: "Pfizer NYHQ Fit-Out, 66 Hudson Blvd.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 98,
        name: "Plumber's Union, Local #1, 50-02 5thSt., LIC, NY",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 99,
        name: "Salvatore Ferragamo, Brookfield Place, 200 Vesey St.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 100,
        name: "Staten Island Mall, Staten Island, NY",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 101,
        name: "Thurgood Marshall Courthouse, 40 Centre St.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 102,
        name: "Tiffany & Co., 555 Madison Ave.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 103,
        name: "Time Warner, 40 Hudson Yards",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 104,
        name: "United Nations Development Corp., 1 UN Plaza, 26th Fl.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    {
        id: 105,
        name: "Anderson, Kill & Olick, 1251 Avenue of the Americas",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 106,
        name: "Empire State Realty Trust, 112 W. 34thSt., 12th Floor",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 107,
        name: "Grand Hyatt, 109 E. 42nd St.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 108,
        name: "Hudson Hotel, 356 W. 58th St.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 109,
        name: "Milford Plaza Hotel, 700 8th Ave.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 110,
        name: "Morgans Hotel, 237 Madison Ave.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 111,
        name: "New York Edition / Marriott, 5 Madison Ave.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 112,
        name: "Sheraton NY Hotel, 811 Seventh Ave.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 113,
        name: "St. Regis Hotel, 2 E. 55th St.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 114,
        name: "The Mark Hotel, 25 E. 77th St.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 115,
        name: "The New York Marriott East Side, 525 Lexington Ave",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 116,
        name: "The Westin Grand Central Hotel, 212 E. 42nd St.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 117,
        name: "Venable, 1270 Avenue of the Americas",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 118,
        name: "Willis Towers Watson, 200 Liberty St.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 119,
        name: "Barclays Capital, 745 7th Ave., 15th Floor",
        category: PROJECT_CATEGORIES.TRADING,
        featured: false,
    },
    {
        id: 120,
        name: "JP Morgan Chase GIO, 320 Park Ave., 14th Floor",
        category: PROJECT_CATEGORIES.TRADING,
        featured: false,
    },
    {
        id: 121,
        name: "Morgan Stanley, 750 7th Ave., Floors 12,14,18,19 & 29",
        category: PROJECT_CATEGORIES.TRADING,
        featured: true,
    },
    {
        id: 122,
        name: "Morgan Stanley, 1585 Broadway, Various Projects/Multiple Floor Fit-Outs",
        category: PROJECT_CATEGORIES.TRADING,
        featured: false,
    },

    {
        id: 127,
        name: "Morgan Stanley, 1 New York Plaza, 36th Floor Electrical & Telecom",
        category: PROJECT_CATEGORIES.TRADING,
        featured: false,
    },
    {
        id: 128,
        name: "Morgan Stanley, 1 New York Plaza, Floor 35, 37 & 38",
        category: PROJECT_CATEGORIES.TRADING,
        featured: false,
    },
    {
        id: 129,
        name: "Societe Generale, 245 Park Ave., Floors 6,7,8 & 9",
        category: PROJECT_CATEGORIES.TRADING,
        featured: false,
    },
    {
        id: 130,
        name: "Barclays Capital, 745 7th Ave.",
        category: PROJECT_CATEGORIES.DATA_CENTERS,
        featured: false,
    },
    {
        id: 131,
        name: "Martha Stewart Living, 601 W. 26th St.",
        category: PROJECT_CATEGORIES.DATA_CENTERS,
        featured: false,
    },
    {
        id: 132,
        name: "Memorial Sloan Kettering Cancer Center, 515 Madison Ave.",
        category: PROJECT_CATEGORIES.DATA_CENTERS,
        featured: true,
    },
    {
        id: 133,
        name: "New York Institute of Technology, 26 W. 61st St.",
        category: PROJECT_CATEGORIES.DATA_CENTERS,
        featured: false,
    },
    {
        id: 134,
        name: "Resorts World New York, 110-00 Rockaway Blvd., Jamaica, NY",
        category: PROJECT_CATEGORIES.DATA_CENTERS,
        featured: false,
    },
    {
        id: 135,
        name: "The Sheraton New York Hotel, 811 Seventh Ave.",
        category: PROJECT_CATEGORIES.DATA_CENTERS,
        featured: false,
    },
    {
        id: 136,
        name: "Thurgood Marshall Courthouse, 40 Centre St.",
        category: PROJECT_CATEGORIES.DATA_CENTERS,
        featured: false,
    },
    {
        id: 137,
        name: "Barclays Capital Skyline Signage/Rebranding at 745 7th Ave.",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 138,
        name: "Guggenheim Museum, 345 Hudson St.",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 139,
        name: "Hudson Hotel “Rave” Night Club, 356 W. 58th St",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 140,
        name: "Isamu Noguchi Foundation & Garden Museum, Long Island City, NY",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 141,
        name: "Major League Baseball Headquarters, 245 Park Ave.",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 142,
        name: "Martha Stewart Living Omnimedia Studios, 601 W. 26th St.",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 143,
        name: "Morgans Hotel Lobby, 237 Madison Ave.",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 144,
        name: "New York University, Tisch Hall of Arts Dance Studios, 726 Broadway",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 145,
        name: "Resorts World New York, Jamaica, NY",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 146,
        name: "St. John's University, Little Theater, Jamaica, NY",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 147,
        name: "St. Regis Hotel Lobby Lighting, 2 E. 55th St.",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 148,
        name: "Tiffany & Co., 555 Madison Ave.",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 149,
        name: "Tiffany & Co./Louis Vuitton Flagship Store, 727 Fifth Ave.",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 150,
        name: "Little Nell Hotel",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 151,
        name: "Wells Fargo, 20 Hudson Yards",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 152,
        name: "JPMC , NY FRB Rock Center, 1230 Avenue of the Americas, New York, NY.",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 153,
        name: "Barclay's Capital NYC Headquarters Electrical Infrastructure Refurbishment",
        category: PROJECT_CATEGORIES.FINANCIAL,
        featured: false,
    },
    {
        id: 154,
        name: "Tiffany’s 727 5th Ave.",
        category: PROJECT_CATEGORIES.SPECIALTY,
        featured: false,
    },
    {
        id: 156,
        name: "St. John’s University Little Theater",
        category: PROJECT_CATEGORIES.EDUCATION_MEDICAL,
        featured: false,
    },
    {
        id: 157,
        name: "Telx, 111 8th Ave",
        category: PROJECT_CATEGORIES.DATA_CENTERS,
        featured: false,
    },
    {
        id: 158,
        name: "Gerber Bar at the Weston Grand Central Hotel, 212 E. 42nd St.",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 159,
        name: "Sheraton Ballroom Lighting, 811 Seventh Avenue",
        category: PROJECT_CATEGORIES.PROFESSIONAL,
        featured: false,
    },
    {
        id: 160,
        name: "Morgans Hotel Lobby Lighting, 237 Madison Ave.",
        category: PROJECT_CATEGORIES.CORPORATE,
        featured: false,
    },
    ...maintenanceProjects,
].sort((a, b) => a.name.localeCompare(b.name));

// Usage in filter component
export const FILTER_OPTIONS = [
    'All Projects',
    'Featured Projects',
    ...Object.values(PROJECT_CATEGORIES)
] as const;

export type FilterOption = typeof FILTER_OPTIONS[number];